apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: zach-test
  namespace: default
  labels:
    ccm: azure
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KThreesControlPlane
    name: zach-test-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureCluster
    name: zach-test
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureCluster
metadata:
  name: zach-test
  namespace: default
spec:
  location: eastus
  networkSpec:
    vnet:
      name: zach-test-vnet
  resourceGroup: zach-test
  subscriptionID: bbda620e-ad6d-4440-8ba0-ba1297702503
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KThreesControlPlane
metadata:
  name: zach-test-control-plane
  namespace: default
spec:
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AzureMachineTemplate
    name: zach-test-control-plane
  kthreesConfigSpec:
    files:
    - contentFrom:
        secret:
          key: control-plane-azure.json
          name: zach-test-control-plane-azure-json
      owner: root:root
      path: /etc/kubernetes/azure.json
      permissions: "0644"
  replicas: 1
  version: v1.20.0+k3s2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachineTemplate
metadata:
  name: zach-test-control-plane
  namespace: default
spec:
  template:
    spec:
      location: eastus
      osDisk:
        diskSizeGB: 128
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      sshPublicKey: ""
      vmSize: Standard_D2s_v3
      image:
        marketplace:
          publisher: Canonical
          sku: 18.04-LTS
          offer: UbuntuServer
          version: latest
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AzureMachineTemplate
metadata:
  name: zach-test-md-0
  namespace: default
spec:
  template:
    spec:
      location: eastus
      osDisk:
        diskSizeGB: 128
        managedDisk:
          storageAccountType: Premium_LRS
        osType: Linux
      sshPublicKey: ""
      vmSize: Standard_D2s_v3
      image:
        marketplace:
          publisher: Canonical
          sku: 18.04-LTS
          offer: UbuntuServer
          version: latest
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: KThreesConfigTemplate
metadata:
  name: zach-test-md-0
  namespace: default
spec:
  template:
    spec:
      files:
      - contentFrom:
          secret:
            key: worker-node-azure.json
            name: zach-test-md-0-azure-json
        owner: root:root
        path: /etc/kubernetes/azure.json
        permissions: "0644"
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: zach-test
  name: zach-test-md-0
  namespace: default
spec:
  clusterName: zach-test
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      version: v1.20.0+k3s2
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KThreesConfigTemplate
          name: zach-test-md-0
      clusterName: zach-test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AzureMachineTemplate
        name: zach-test-md-0
