name: Pull Request Validation
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO_VERSION: "1.20"

jobs:
  validate:
    name: "Validate ${{ matrix.target }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["lint", "test-bootstrap", "test-controlplane"]

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: ${{ matrix.target }}
        run: make ${{ matrix.target }}
